name: JS Actions

on:
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: action-two
      - name: install npm hello packages
        run: |
         cd ./.github/actions/hello-world
         npm install
      - name: hello-action
        uses: ./.github/actions/hello-world
      - name: install npm joke packages
        run: |
         cd ./.github/actions/joke-action
         npm install
      - name: my joke
        uses: ./.github/actions/joke-action
        id: jokes
      - name: create issue
        uses: ./.github/actions/issue-maker
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          joke: ${{steps.jokes.outputs.joke-output}}
