name: JS Actions

on: [push]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: install npm packages
        run: |
         cd ./.github/actions/hello-world
         npm install
      - name: hello-action
        uses: ./.github/actions/hello-world
        with:
          first-greeting: "test1"
          second-greeting: "test2"
          third-greeting: "test3"