name: JS Actions

on:
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: action-two
      - name: install npm packages
        run: |
         cd ~/.github/actions/hello-world
         npm install
         cd ~/.github/actions/joke-action
         npm install
      - name: hello-action
        uses: ~/.github/actions/hello-world
      - name: my joke
        uses: ~/.github/actions/joke-action